# Generated by Django 4.0.3 on 2022-03-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_conent',
            new_name='tutorial_content',
        ),
    ]
