# Generated by Django 4.0.3 on 2022-04-03 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_tutorial_conent_tutorial_tutorial_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 5, 24, 42, 16379), verbose_name='date published'),
        ),
    ]
